global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Traefik metrics
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8082"]

  # Container-level metrics
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  # Host metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
